version: "3"

services:
  db:
    image: "postgres:14"
    container_name: dock-db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: dock-backend
    environment:
      - DJANGO_DEBUG
      - DJANGO_SECRET_KEY
      - DJANGO_CORS_ALLOWED_ORIGINS
      - DJANGO_DB_TYPE=postgres
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    volumes:
      - "./logs/backend:/app/logs"
      - "backend_static:/app/static"
      - "backend_media:/app/private_media"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: "nginx:1.23"
    container_name: dock-nginx
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./logs/nginx:/var/log/nginx"
      - "./frontend/dist:/var/www/frontend:ro"
      - "backend_static:/var/www/backend/static:ro"
      - "backend_media:/var/www/backend/media:ro"
    ports:
      - "${NGINX_HTTP_PORT}:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
  backend_static:
  backend_media:
